### ISSUE TITLE
napalm-ansible need to add separate develop branch

### ISSUE THREAD

**Issue by ktbyers** [napalm-automation/napalm-ansible#61] opened 2017-06-14 16:49 UTC
Also need to add a set of unit tests to it.

Depending on the frequency of changes we also might to periodically make a release to that people can use a specific version of napalm-ansible without it being changed.

**Comment by dbarrosop** [comment] 2017-06-15 06:58
> napalm-ansible need to add separate develop branch

I agree. However, the problem is that if users clone the repo git will default to `develop` so we won't solve any problem unless we change the instructions to install this. See last point.

> Also need to add a set of unit tests to it.

Yep, I was thinking exactly that after the issue yesterday. `napalm-base` could include a `DeviceMock` driver that just returns dummy output. That way we could use that driver to run unittests here and potentially on other tools.

> release

I agree. We should also make sure people install from the tarballs or pinning to tags when clonning the repo (we could have a `latest` tag to simplify the instructions).

**Comment by dbarrosop** [comment] 2017-06-15 07:04
master/develop branch has been fixed already. Let me know what you need about the other points and we can start working on it.

**Comment by targuan** [comment] 2017-06-18 21:11
The ansible project is also testing with integration tests via playbooks.
I think it would make sense to also test napalm-ansible through playbooks against several ansible versions.

I made an exemple in my [feature/tests](https://github.com/targuan/napalm-ansible/tree/feature/tests) branch with a [dummy driver](https://github.com/targuan/napalm-dummy) in order to assess its benefit.

**Comment by dbarrosop** [comment] 2017-06-19 10:59
That's great! Would be nice to have the "dummy" driver inside `napalm-base` I think as it could be useful for other stuff. It would also be great if it could do two things:

1. Have an optional argument where you can pass a path (relative to where the driver is installed).
2. Methods return the contents of files with the same name as the method in the path (1) or `NotImplementedException` if none exist.

That way we could build test cases as well. So it would work something like this:

```
driver = get_network_driver("dummy")
d1 = dummy(hostname, username, password, timeout, optional_args={"mock_path": "blah"})

# contents in ./blah/
#     show_facts.json
#     open.json
#     close.json

d1.open()
print(d.show_facts())
# file content is deserialized and returned
print(d.show_interfaces())
# as no file called `show_interfaces.json` exists return NotImplementedException
d1.close()
```

@targuan let me know if this is something you want to work on, time is not an issue here.

**Comment by dbarrosop** [comment] 2017-06-19 11:05
Actually, it doesn't make sense that the path is relative to the driver. It should be absolute so the test using the `dummy` driver can actually provide the files for the test case it wants to test.

**Comment by dbarrosop** [comment] 2017-07-01 13:11
I have implemented the `MockDriver` here:

https://github.com/napalm-automation/napalm-base/pull/269/files

With it should be easy to test the modules with it.

Comments are welcome.

**Comment by dbarrosop** [comment] 2017-07-02 08:47
Testing PR:

https://github.com/napalm-automation/napalm-ansible/pull/66
https://travis-ci.org/napalm-automation/napalm-ansible/builds/249281235

**Comment by dbarrosop** [comment] 2017-07-09 10:42
Should we close this one @ktbyers?

**Closed as completed** 2017-07-10 16:31 UTC
