### ISSUE TITLE
install config change failed

### ISSUE THREAD

**Issue by davehs30** [napalm-automation/napalm-ansible#26] opened 2016-05-03 19:21 UTC
I have attached the playbook and the config file that is trying to be updated.  
[fortigate.config-update.yml.txt](https://github.com/napalm-automation/napalm-ansible/files/247581/fortigate.config-update.yml.txt)

[new.conf.txt](https://github.com/napalm-automation/napalm-ansible/files/247583/new.conf.txt)

This is the output that I am getting from the playbook:

ansible-tst:~/fortigate# ansible-playbook fortigate.config-update.yml 

PLAY [firewall] **************************************************************\* 

GATHERING FACTS **************************************************************\* 
ok: [homefw]

TASK: [update config] ********************************************************\* 
failed: [homefw] => {"failed": true}
msg: cannot install config: 

FATAL: all hosts have already failed -- aborting

PLAY RECAP *******************************************************************\* 
           to retry, use: --limit @/root/fortigate.config-update.retry

homefw                     : ok=1    changed=0    unreachable=0    failed=1   

---

Many Thanks!

**Comment by dbarrosop** [comment] 2016-05-03 20:43
Can you make sure you have the latest code for `napalm_install_config.py`? It's not going to fix anything but it gives a nicer error message that might help us.

**Comment by davehs30** [comment] 2016-05-03 21:42
Confirmed version 2.1 in the napalm_install_config.py,  down loaded the 'raw' file and ran diff just to confirm nothing was changed.

**Comment by dbarrosop** [comment] 2016-05-03 22:57
Can you try running with -vvvv?

**Comment by davehs30** [comment] 2016-05-03 23:23
Sure;

ansible-tst:~/fortigate# ansible-playbook -vvvv fortigate.config-update.yml 

PLAY [firewall] **************************************************************\* 

GATHERING FACTS **************************************************************\* 
<homefw> REMOTE_MODULE setup
<homefw> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1462317778.87-210030826951668 && echo $HOME/.ansible/tmp/ansible-tmp-1462317778.87-210030826951668']
<homefw> PUT /tmp/tmpfichws TO /root/.ansible/tmp/ansible-tmp-1462317778.87-210030826951668/setup
<homefw> EXEC ['/bin/sh', '-c', u'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1462317778.87-210030826951668/setup; rm -rf /root/.ansible/tmp/ansible-tmp-1462317778.87-210030826951668/ >/dev/null 2>&1']
ok: [homefw]

TASK: [update config] ********************************************************\* 
<homefw> REMOTE_MODULE napalm_install_config hostname=homefw username=admin dev_os=fortios password=VALUE_HIDDEN optional_args="fortios_vdom=global" config_file=/root/fortigate/compiled/homefw/new.conf commit_changes=true replace_config=false get_diffs=true diff_file=/root/fortigate/compiled/homefw/diff.conf
<homefw> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1462317778.97-44118767300883 && echo $HOME/.ansible/tmp/ansible-tmp-1462317778.97-44118767300883']
<homefw> PUT /tmp/tmpaUQNDT TO /root/.ansible/tmp/ansible-tmp-1462317778.97-44118767300883/napalm_install_config
<homefw> EXEC ['/bin/sh', '-c', u'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1462317778.97-44118767300883/napalm_install_config; rm -rf /root/.ansible/tmp/ansible-tmp-1462317778.97-44118767300883/ >/dev/null 2>&1']
failed: [homefw] => {"failed": true}
msg: cannot install config: 

FATAL: all hosts have already failed -- aborting

PLAY RECAP *******************************************************************\* 
           to retry, use: --limit @/root/fortigate.config-update.retry

homefw                     : ok=1    changed=0    unreachable=0    failed=1

**Comment by mbuschmann28** [comment] 2016-05-03 23:58
What version of python are you using? (python -V). I've seen something similar with <2.7 version. If you suspect that might be the case, you can try setting the interpreter version manually in your command as a test:

ansible-playbook  fortigate.config-update.yml --extra-vars "ansible_python_interpreter=/<path-to-python-2.7>" -vvvv

-mike

**Comment by mbuschmann28** [comment] 2016-05-04 00:00
Sorry, looks like git omitted my example path (you would replace with your actual path to 2.7): 'ansible-playbook fortigate.config-update.yml --extra-vars "ansible_python_interpreter=/bin/python2.7" -vvvv

**Comment by davehs30** [comment] 2016-05-04 01:08
output looks the same to me.

ansible-tst:~/fortigate# ansible-playbook fortigate.config-update.yml --extra-vars "ansible_python_interpreter=/usr/bin/python2.7" -vvvv

PLAY [firewall] **************************************************************\* 

GATHERING FACTS **************************************************************\* 
<homefw> REMOTE_MODULE setup
<homefw> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1462324029.86-258530902571369 && echo $HOME/.ansible/tmp/ansible-tmp-1462324029.86-258530902571369']
<homefw> PUT /tmp/tmpb6gjK0 TO /root/.ansible/tmp/ansible-tmp-1462324029.86-258530902571369/setup
<homefw> EXEC ['/bin/sh', '-c', u'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python2.7 /root/.ansible/tmp/ansible-tmp-1462324029.86-258530902571369/setup; rm -rf /root/.ansible/tmp/ansible-tmp-1462324029.86-258530902571369/ >/dev/null 2>&1']
ok: [homefw]

TASK: [update config] ********************************************************\* 
<homefw> REMOTE_MODULE napalm_install_config hostname=homefw username=admin dev_os=fortios password=VALUE_HIDDEN optional_args="fortios_vdom=global" config_file=/root/fortigate/compiled/homefw/new.conf commit_changes=true replace_config=false get_diffs=true diff_file=/root/fortigate/compiled/homefw/diff.conf
<homefw> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1462324029.98-38038107993480 && echo $HOME/.ansible/tmp/ansible-tmp-1462324029.98-38038107993480']
<homefw> PUT /tmp/tmpvLpSqj TO /root/.ansible/tmp/ansible-tmp-1462324029.98-38038107993480/napalm_install_config
<homefw> EXEC ['/bin/sh', '-c', u'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python2.7 /root/.ansible/tmp/ansible-tmp-1462324029.98-38038107993480/napalm_install_config; rm -rf /root/.ansible/tmp/ansible-tmp-1462324029.98-38038107993480/ >/dev/null 2>&1']
failed: [homefw] => {"failed": true}
msg: cannot install config: 

FATAL: all hosts have already failed -- aborting

PLAY RECAP *******************************************************************\* 
           to retry, use: --limit @/root/fortigate.config-update.retry

homefw                     : ok=1    changed=0    unreachable=0    failed=1

**Comment by mbuschmann28** [comment] 2016-05-04 18:16
So if you have confirmed that you're using an updated version of python and its still not working, then my best guess is that you have something defined in your configuration template that napalm_install_config is not happy with, maybe a special character or something? I would try reducing your template config down to something very simple to a point where it works, and then working in the reset to debug what might be the cause..

-mike

**Comment by dbarrosop** [comment] 2016-05-04 20:27
It would be interesting if you could try with ansible directly without ansible. It might give some more information.

**Comment by davehs30** [comment] 2016-05-04 21:10
Looks like I have a problem with Python and Napalm.  I am also getting errors when I go to upgrade python modules.  Will build a new test system.

ansible-tst:~/fortigate# cl_napalm_configure --user admin --password ***\* --vendor fortios --strategy merge --optional_arges 'fortios_vdom=global' compiled/homefw/new.conf homefw
Traceback (most recent call last):
  File "/usr/bin/cl_napalm_configure", line 9, in <module>
    load_entry_point('napalm-base==0.13.0', 'console_scripts', 'cl_napalm_configure')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/**init**.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/**init**.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/**init**.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/**init**.py", line 2235, in resolve
    module = **import**(self.module_name, fromlist=['**name**'], level=0)
ImportError: No module named clitools.cl_napalm_configure

**Comment by dbarrosop** [comment] 2016-05-04 21:29
I recommend you to use `virtualenv` and `pip`.

**Comment by mbuschmann28** [comment] 2016-05-04 23:17
JFYI - I've actually had issues getting Ansible (ver 1.9.4) to use the correct python version even when using virtualenv.. Setting it manually via the 'ansible_python_interpreter' var is the only thing that has worked for me. I would recommend a new environment using vagrant.

**Comment by ktbyers** [comment] 2016-05-05 01:25
This is normal with Ansible...you pretty much always want to set the ansible_python_interpreter (especially with a virtualenv).

**Comment by dbarrosop** [comment] 2016-05-05 15:20
As @ktbyers setting `ansible_python_interpreter: "/usr/bin/env python"` as a global var on your playbook should work fine. If it doesn't in your particular use case for some reason, please, report it to the `ansible` community, I am sure they would like to know.

**Comment by ktbyers** [comment] 2016-09-15 15:53
Nothing else to do on this issue...so closing.

**Closed as completed by ktbyers** 2016-09-15 15:53 UTC
